#pragma warning disable CA1416 // Runtime OS guards in TTerminalWindow make platform calls safe.
using System.IO;
using TSharpVision.Constants;
using TSharpVision.Terminal;
using TSharpVision.Text;

namespace TSharpVision.Samples.TVTerm;

/// <summary>
/// TVTerm — TSharpVision Turbo Vision terminal demo. Hosts terminal windows
/// inside a Turbo Vision desktop and exposes the TTerminal feature surface
/// through menu commands. All terminal logic lives in <see cref="TTerminal"/>
/// (core) and in the <c>TSharpVision.Terminal</c> extension; this class is
/// the UI shell.
/// </summary>
public sealed class TVTermApp : TApplication
{
    // Context IDs must match the compiled TVTERM.HLP (generated by svhc).
    // The Index topic is always assigned id 1 by the .topic Index=1 directive.
    private const ushort HelpCtxIndex    = 1;

    private THelpFile? _helpFile;
    private Fpstream? _helpStream;
    private readonly TVTermConfig _config;
    private int _windowCascade;
    private string _lastFindText = string.Empty;

    public TVTermApp()
        : base()
    {
        _config = TVTermConfig.Load();
    }

    // ------------------------------------------------------------------
    // Menu / Status line / Help
    // ------------------------------------------------------------------

    public override TStatusLine InitStatusLine(TRect r)
    {
        r.a.y = r.b.y - 1;
        return new TStatusLine(r,
            new TStatusDef(0, 0xFFFF) +
            new TStatusItem("~F1~ Help", Keys.kbF1, Views.cmHelp) +
            new TStatusItem("~F2~ Menu", Keys.kbF2, Views.cmMenu) +
            new TStatusItem("~F3~ Run", Keys.kbF3, Commands.cmRunCommand) +
            new TStatusItem("~F4~ New", Keys.kbF4, Commands.cmNewTerminal) +
            new TStatusItem("~F9~ Interrupt", Keys.kbF9, Commands.cmInterrupt) +
            new TStatusItem("~Alt-X~ Exit", Keys.kbAltX, Views.cmQuit) +
            new TStatusItem(null, Keys.kbF10, Views.cmMenu) +
            new TStatusItem(null, Keys.kbAltF3, Views.cmClose) +
            new TStatusItem(null, Keys.kbF5, Views.cmZoom) +
            new TStatusItem(null, Keys.kbCtrlF5, Views.cmResize)
        );
    }

    public override TMenuBar InitMenuBar(TRect r)
    {
        r.b.y = r.a.y + 1;
        return new TMenuBar(r,
            new TSubMenu("~F~ile", Keys.kbAltF) +
                new TMenuItem("~N~ew Terminal",      Commands.cmNewTerminal,     Keys.kbF4, Views.hcNoContext, "F4") +
                new TMenuItem("New ~F~ake Terminal", Commands.cmNewFakeTerminal, Keys.kbNoKey, Views.hcNoContext) +
                new TMenuItem("~R~un Command...",    Commands.cmRunCommand,      Keys.kbF3, Views.hcNoContext, "F3") +
                new TMenuItem("~O~pen Log File...",  Commands.cmOpenLog,         Keys.kbNoKey, Views.hcNoContext) +
                new TMenuItem("~S~ave Output...",    Commands.cmSaveOutput,      Keys.kbNoKey, Views.hcNoContext) +
                TMenuItem.NewLine() +
                new TMenuItem("~C~lose",             Views.cmClose,              Keys.kbAltF3, Views.hcNoContext, "Alt-F3") +
                new TMenuItem("E~x~it",              Views.cmQuit,               Keys.kbAltX, Views.hcNoContext, "Alt-X") +
            new TSubMenu("~E~dit", Keys.kbAltE) +
                new TMenuItem("~C~opy",              Commands.cmCopy,            Keys.kbCtrlIns, Views.hcNoContext, "Ctrl-Ins") +
                new TMenuItem("~P~aste",             Commands.cmPaste,           Keys.kbShiftIns, Views.hcNoContext, "Shift-Ins") +
                new TMenuItem("Select ~A~ll",        Commands.cmSelectAll,       Keys.kbNoKey, Views.hcNoContext) +
                new TMenuItem("Clear ~S~election",   Commands.cmClearSelection,  Keys.kbNoKey, Views.hcNoContext) +
                TMenuItem.NewLine() +
                new TMenuItem("~F~ind...",           Commands.cmFind,            Keys.kbNoKey, Views.hcNoContext) +
                new TMenuItem("Find ~N~ext",         Commands.cmFindNext,        Keys.kbNoKey, Views.hcNoContext) +
            new TSubMenu("~V~iew", Keys.kbAltV) +
                new TMenuItem("~C~lear Screen",      Commands.cmClearScreen,     Keys.kbNoKey, Views.hcNoContext) +
                new TMenuItem("Scrollback ~T~op",    Commands.cmScrollTop,       Keys.kbNoKey, Views.hcNoContext) +
                new TMenuItem("Scrollback ~B~ottom", Commands.cmScrollBottom,    Keys.kbNoKey, Views.hcNoContext) +
                TMenuItem.NewLine() +
                new TMenuItem("Toggle ~A~NSI",       Commands.cmToggleAnsi,      Keys.kbNoKey, Views.hcNoContext) +
            new TSubMenu("~S~ession", Keys.kbAltS) +
                new TMenuItem("~I~nterrupt",         Commands.cmInterrupt,       Keys.kbF9, Views.hcNoContext, "F9") +
                new TMenuItem("~R~estart",           Commands.cmRestart,         Keys.kbNoKey, Views.hcNoContext) +
                new TMenuItem("Send ~E~OF",          Commands.cmSendEof,         Keys.kbNoKey, Views.hcNoContext) +
                new TMenuItem("~K~ill Process",      Commands.cmKill,            Keys.kbNoKey, Views.hcNoContext) +
            new TSubMenu("~T~ools", Keys.kbAltT) +
                new TMenuItem("~K~ey Inspector",     Commands.cmKeyInspector,    Keys.kbNoKey, Views.hcNoContext) +
                new TMenuItem("~U~nicode Demo",      Commands.cmUnicodeDemo,     Keys.kbNoKey, Views.hcNoContext) +
                new TMenuItem("~A~NSI Demo",         Commands.cmAnsiDemo,        Keys.kbNoKey, Views.hcNoContext) +
                new TMenuItem("~P~erformance Demo",  Commands.cmPerfDemo,        Keys.kbNoKey, Views.hcNoContext) +
                new TMenuItem("~S~election Demo", Commands.cmSelectionDemo, Keys.kbNoKey) +
                new TMenuItem("Pipe: ~d~otnet --info", Commands.cmPipeDemo, Keys.kbNoKey) +
                new TMenuItem("Short PT~Y~ command", Commands.cmPtyDemo, Keys.kbNoKey) +
                new TMenuItem("Interactive s~h~ell", Commands.cmShellDemo, Keys.kbNoKey) +
            new TSubMenu("~O~ptions", Keys.kbAltO) +
                new TMenuItem("~T~erminal Settings...", Commands.cmTerminalSettings, Keys.kbNoKey, Views.hcNoContext) +
                new TMenuItem("~U~I Colors...",         Commands.cmUiColors,         Keys.kbNoKey, Views.hcNoContext) +
                new TMenuItem("T~e~rminal Colors...",   Commands.cmColorMapping,     Keys.kbNoKey, Views.hcNoContext) +
                new TMenuItem("~K~eyboard Mapping...",  Commands.cmKeyboardMapping,  Keys.kbNoKey, Views.hcNoContext) +
            new TSubMenu("~H~elp", Keys.kbAltH) +
                new TMenuItem("~C~ontents",          Commands.cmHelpContents,    Keys.kbF1, Views.hcNoContext, "F1") +
                new TMenuItem("~A~bout TVTerm",      Commands.cmAbout,           Keys.kbNoKey, Views.hcNoContext)
        );
    }

    public override THelpFile GetHelpFile()
    {
        EnsureHelpFile();
        return _helpFile!;
    }

    private void EnsureHelpFile()
    {
        if (_helpFile != null) return;
        THelpFile.RegisterStreamableTypes();
        string hlpPath = Path.Combine(System.AppContext.BaseDirectory, "Assets", "Help", "TVTERM.HLP");
        if (!File.Exists(hlpPath)) return;
        _helpStream = new Fpstream(hlpPath);
        _helpFile = new THelpFile(
            _helpStream,
            new HelpV1LoadOptions { LegacyEncoding = LegacyTextEncodings.Cp437 });
    }

    public override void ShutDown()
    {
        _helpStream?.Close();
        _helpStream = null;
        _helpFile = null;
        base.ShutDown();
    }

    // ------------------------------------------------------------------
    // Event dispatch
    // ------------------------------------------------------------------

    public override void HandleEvent(ref TEvent ev)
    {
        base.HandleEvent(ref ev);
        if (ev.What != Events.evCommand) return;

        ushort cmd = ev.message.command;
        switch (cmd)
        {
            case Commands.cmNewTerminal:      OpenNewTerminal(); break;
            case Commands.cmNewFakeTerminal:  OpenFakeTerminal(); break;
            case Commands.cmRunCommand:       OpenRunCommandDialog(); break;
            case Commands.cmOpenLog:          OpenLogFile(); break;
            case Commands.cmSaveOutput:       SaveOutput(); break;

            case Commands.cmCopy:             DoCopy(); break;
            case Commands.cmPaste:            DoPaste(); break;
            case Commands.cmSelectAll:        DoSelectAll(); break;
            case Commands.cmClearSelection:   DoClearSelection(); break;
            case Commands.cmFind:             DoFind(); break;
            case Commands.cmFindNext:         DoFindNext(); break;

            case Commands.cmClearScreen:      WithTerm(t => t.Clear()); break;
            case Commands.cmScrollTop:        WithTerm(t => t.ScrollToTop()); break;
            case Commands.cmScrollBottom:     WithTerm(t => t.ScrollToBottom()); break;
            case Commands.cmToggleWrap:       NotImplementedMsg("Line wrapping is always on; toggle support requires core API changes."); break;
            case Commands.cmToggleAnsi:       DoToggleAnsi(); break;

            case Commands.cmInterrupt:        WithWindow(w => w.Interrupt()); break;
            case Commands.cmRestart:          WithWindow(w => w.RestartExternalSession()); break;
            case Commands.cmSendEof:          WithWindow(w => w.SendEof()); break;
            case Commands.cmKill:             WithWindow(w => w.StopExternalSession()); break;

            case Commands.cmKeyInspector:     OpenKeyInspector(); break;
            case Commands.cmUnicodeDemo:      OpenScriptedDemo("Unicode Demo", TerminalDemos.RunUnicodeDemo); break;
            case Commands.cmAnsiDemo:         OpenScriptedDemo("ANSI Demo",    TerminalDemos.RunAnsiDemo); break;
            case Commands.cmPerfDemo:         OpenScriptedDemo("Performance Demo", s => TerminalDemos.RunPerformanceDemo(s, 64)); break;
            case Commands.cmSelectionDemo:    OpenSelectionDemo(); break;
            case Commands.cmPipeDemo:         OpenSessionDemo(SessionKind.Pipe); break;
            case Commands.cmPtyDemo:          OpenSessionDemo(SessionKind.Pty); break;
            case Commands.cmShellDemo:        OpenSessionDemo(SessionKind.Shell); break;

            case Commands.cmTerminalSettings: TerminalSettingsDialog.ShowDialog(DeskTop!, _config); break;
            case Commands.cmUiColors:         OpenUiColors(); break;
            case Commands.cmColorMapping:
                ColorMappingDialog.ShowDialog(DeskTop!, _config);
                ApplyColorMapToAllTerminals();
                break;
            case Commands.cmKeyboardMapping:  KeyboardMappingDialog.ShowDialog(DeskTop!, _config); break;

            case Commands.cmHelpContents:     OpenHelp(); break;
            case Commands.cmAbout:            AboutDialog.ShowDialog(DeskTop!); break;

            default: return;
        }
        ClearEvent(ref ev);
    }

    // ------------------------------------------------------------------
    // File menu actions
    // ------------------------------------------------------------------

    private TRect NewWindowRect()
    {
        int x = 2 + (_windowCascade % 6);
        int y = 1 + (_windowCascade % 5);
        _windowCascade++;
        int w = System.Math.Min(80, DeskTop!.size.x - x - 1);
        int h = System.Math.Min(22, DeskTop!.size.y - y - 1);
        return new TRect(x, y, x + w, y + h);
    }

    private TTerminalWindow OpenWindow(string title)
    {
        var win = new TTerminalWindow(NewWindowRect(), title, Views.wnNoNumber);
        DeskTop!.Insert(win);
        ApplyColorMap(win.Terminal);
        return win;
    }

    private void ApplyColorMap(TTerminal term)
    {
        if (_config.ColorMap is { Length: >= 16 } map)
            term.ApplyColorMap(map);
    }

    private void ApplyColorMapToAllTerminals()
    {
        DeskTop?.ForEachView(v =>
        {
            if (v is TTerminalWindow tw)
                ApplyColorMap(tw.Terminal);
        });
    }

    private void OpenNewTerminal()
    {
        var win = OpenWindow("Terminal");
        win.EmitBanner("Local command terminal. Type 'help' for built-in demo commands.\n");
        win.EmitBanner("Use Session → Restart to relaunch the last external session.\n\n");
        WireDemoCommandLoop(win);

        // If user configured a default external session, start it.
        switch (_config.DefaultSessionMode)
        {
            case DefaultSessionMode.Pty when PtyAvailability.IsAnyPtySupported:
                win.StartSession(new SessionSpec
                {
                    Kind = SessionKind.Shell,
                    FileName = DefaultShell(),
                    Arguments = string.Empty,
                    RawSession = true,
                });
                break;
            case DefaultSessionMode.Fake:
                win.StartSession(new SessionSpec { Kind = SessionKind.Fake });
                break;
            // Pipe / InMemory: leave the InMemory command loop running.
        }
    }

    private void OpenFakeTerminal()
    {
        var win = OpenWindow("Fake Terminal");
        win.EmitBanner("FakePtyTerminalSession — deterministic, no real process.\n");
        WireDemoCommandLoop(win);
        win.StartSession(new SessionSpec { Kind = SessionKind.Fake });
    }

    private void OpenRunCommandDialog()
    {
        if (DeskTop == null) return;
        var r = RunCommandDialog.ShowDialog(DeskTop);
        if (r == null) return;

        var win = OpenWindow($"Run: {r.FileName}");
        win.EmitBanner($"Starting {r.Kind}: {r.FileName} {r.Arguments}\n");
        win.StartSession(new SessionSpec
        {
            Kind = r.Kind,
            FileName = r.FileName,
            Arguments = r.Arguments,
            WorkingDirectory = r.WorkingDirectory,
            RawSession = false,
        });
    }

    private void OpenLogFile()
    {
        if (DeskTop == null) return;
        var fd = new TFileDialog("*.*", "Open Log File", "~F~ile name",
                                 FileDialogOptions.fdOpenButton, 0);
        if (ValidView(fd) == null) return;
        ushort res = DeskTop.ExecView(fd);
        if (res != Views.cmOK) return;
        fd.GetData(out string path);
        if (string.IsNullOrWhiteSpace(path) || !File.Exists(path))
        {
            MsgBox.MessageBox(DeskTop, $"File not found: {path}", MsgBox.mfError | MsgBox.mfOKButton);
            return;
        }

        var win = OpenWindow(Path.GetFileName(path));
        try
        {
            string text = File.ReadAllText(path);
            win.EmitBanner(text);
            if (!text.EndsWith("\n")) win.EmitBanner("\n");
            win.EmitBanner($"-- end of {Path.GetFileName(path)} --\n");
        }
        catch (System.Exception ex)
        {
            win.EmitBanner($"[Error reading file] {ex.Message}\n");
        }
        win.Terminal.InputEnabled = false;
    }

    private void SaveOutput()
    {
        if (DeskTop == null) return;
        var term = ActiveTerminal();
        if (term == null)
        {
            MsgBox.MessageBox(DeskTop, "No active terminal window.", MsgBox.mfInformation | MsgBox.mfOKButton);
            return;
        }
        var fd = new TFileDialog("*.txt", "Save Output", "~F~ile name",
                                 FileDialogOptions.fdOKButton, 0);
        if (ValidView(fd) == null) return;
        ushort res = DeskTop.ExecView(fd);
        if (res != Views.cmOK) return;
        fd.GetData(out string path);
        if (string.IsNullOrWhiteSpace(path)) return;
        try
        {
            File.WriteAllLines(path, term.Lines);
            MsgBox.MessageBox(DeskTop, $"Saved {term.Lines.Count} lines.", MsgBox.mfInformation | MsgBox.mfOKButton);
        }
        catch (System.Exception ex)
        {
            MsgBox.MessageBox(DeskTop, $"Save failed: {ex.Message}", MsgBox.mfError | MsgBox.mfOKButton);
        }
    }

    // ------------------------------------------------------------------
    // Edit menu actions
    // ------------------------------------------------------------------

    private void DoCopy()
    {
        var t = ActiveTerminal();
        if (t == null) return;
        if (t.HasSelection) t.CopySelection();
    }

    private void DoPaste()
    {
        var t = ActiveTerminal();
        if (t == null) return;
        if (ClipboardService.Current.TryGetText(out string text))
            t.PasteText(text);
    }

    private void DoSelectAll()
    {
        var t = ActiveTerminal();
        if (t == null || t.Lines.Count == 0) return;
        var anchor = new TerminalTextPosition(0, 0);
        int lastLine = t.Lines.Count - 1;
        int lastCol = t.Lines[lastLine].Length;
        var active = new TerminalTextPosition(lastLine, lastCol);
        t.SetSelection(anchor, active);
        t.DrawView();
    }

    private void DoClearSelection()
    {
        var t = ActiveTerminal();
        t?.ClearSelection();
        t?.DrawView();
    }

    private void DoFind()
    {
        var t = ActiveTerminal();
        if (t == null) return;
        var r = FindDialog.ShowDialog(DeskTop!, _lastFindText);
        if (r == null) return;
        _lastFindText = r.Text;
        FindAndSelect(t, r.Text, r.CaseSensitive, fromTop: true);
    }

    private void DoFindNext()
    {
        var t = ActiveTerminal();
        if (t == null || string.IsNullOrEmpty(_lastFindText)) return;
        FindAndSelect(t, _lastFindText, caseSensitive: false, fromTop: false);
    }

    private void FindAndSelect(TTerminal t, string needle, bool caseSensitive, bool fromTop)
    {
        var cmp = caseSensitive ? System.StringComparison.Ordinal : System.StringComparison.OrdinalIgnoreCase;
        var lines = t.Lines;
        int startLine = 0, startCol = 0;
        if (!fromTop && t.HasSelection)
        {
            // Continue right after the current selection end. Without access
            // to selection bounds, fall back to a fresh search from line 1
            // past the last hit if we can compute it; otherwise from top.
            // SetSelection doesn't expose getters, so start past the last hit
            // we did via _lastFindHit (tracked below if needed).
        }
        for (int i = startLine; i < lines.Count; i++)
        {
            int col = (i == startLine ? startCol : 0);
            int idx = lines[i].IndexOf(needle, col, cmp);
            if (idx >= 0)
            {
                t.SetSelection(new TerminalTextPosition(i, idx),
                               new TerminalTextPosition(i, idx + needle.Length));
                t.ScrollToBottom();
                t.DrawView();
                return;
            }
        }
        MsgBox.MessageBox(DeskTop!, $"\"{needle}\" not found.", MsgBox.mfInformation | MsgBox.mfOKButton);
    }

    // ------------------------------------------------------------------
    // View menu actions
    // ------------------------------------------------------------------

    private void DoToggleAnsi()
    {
        var t = ActiveTerminal();
        if (t == null) return;
        t.AnsiEnabled = !t.AnsiEnabled;
        t.WriteLine($"[ANSI parsing: {(t.AnsiEnabled ? "on" : "off")}]");
    }

    // ------------------------------------------------------------------
    // Tools menu actions
    // ------------------------------------------------------------------

    private void OpenKeyInspector()
    {
        if (DeskTop == null) return;
        var win = new KeyInspectorWindow(NewWindowRect());
        DeskTop.Insert(win);
    }

    private void OpenSelectionDemo()
    {
        var win = OpenWindow("Selection Demo");
        WireDemoCommandLoop(win);
        ScriptToTerminal(win.Terminal, TerminalDemos.RunSelectionDemo);
    }

    private void OpenSessionDemo(SessionKind kind)
    {
        if (kind != SessionKind.Pipe && !PtyAvailability.IsAnyPtySupported)
        {
            NotImplementedMsg("PTY is unavailable on this platform. Use the pipe demonstration.");
            return;
        }
        bool windows = OperatingSystem.IsWindows();
        var spec = kind switch
        {
            SessionKind.Pipe => new SessionSpec { Kind = kind, FileName = "dotnet", Arguments = "--info" },
            SessionKind.Shell => new SessionSpec { Kind = kind, FileName = DefaultShell(), RawSession = true },
            _ => new SessionSpec { Kind = kind, FileName = windows ? "cmd.exe" : "sh",
                Arguments = windows ? "/c echo Hello from ConPTY" : "-c \"echo Hello from POSIX PTY\"" }
        };
        var win = OpenWindow($"{kind} Demo");
        WireDemoCommandLoop(win);
        win.Terminal.WriteLine("Session menu: interrupt, restart or kill. Shell: type exit to return to local input.");
        win.StartSession(spec);
    }

    private void OpenScriptedDemo(string title, System.Action<InMemoryTerminalSession> script)
    {
        var win = OpenWindow(title);
        win.Terminal.InputEnabled = false;
        // Use the embedded in-memory session via the EmitBanner indirection:
        // run the script directly on a fresh InMemorySession would not show
        // up because TTerminal is attached to the window's own _memSession.
        // Instead drive the embedded session by writing via TTerminal.Write.
        ScriptToTerminal(win.Terminal, script);
    }

    private static void ScriptToTerminal(TTerminal term, System.Action<InMemoryTerminalSession> script)
    {
        // Run the script through a transient session whose output is replayed
        // into the terminal. This keeps the demo scripts session-typed.
        var transient = new InMemoryTerminalSession();
        transient.OutputReceived += (_, e) => term.Write(e.Text);
        transient.StartAsync().GetAwaiter().GetResult();
        script(transient);
        transient.StopAsync().GetAwaiter().GetResult();
        transient.Dispose();
    }

    // ------------------------------------------------------------------
    // Help menu actions
    // ------------------------------------------------------------------

    private void OpenHelp()
    {
        var hf = GetHelpFile();
        if (hf == null)
        {
            MsgBox.MessageBox(DeskTop!,
                "Could not open Assets/Help/DEMOHELP.HLP.",
                MsgBox.mfError | MsgBox.mfOKButton);
            return;
        }
        var win = new THelpWindow(hf, HelpCtxIndex);
        if (ValidView(win) != null)
            ExecuteHelp(win);
    }

    // ------------------------------------------------------------------
    // Helpers
    // ------------------------------------------------------------------

    private TTerminalWindow? ActiveTerminalWindow()
    {
        var v = DeskTop?.current;
        while (v != null)
        {
            if (v is TTerminalWindow ttw) return ttw;
            // walk owner chain — not strictly needed; current usually is the window
            break;
        }
        return null;
    }

    private TTerminal? ActiveTerminal() => ActiveTerminalWindow()?.Terminal;

    private void WithTerm(System.Action<TTerminal> action)
    {
        var t = ActiveTerminal();
        if (t != null) action(t);
    }

    private void WithWindow(System.Action<TTerminalWindow> action)
    {
        var w = ActiveTerminalWindow();
        if (w != null) action(w);
    }

    private void NotImplementedMsg(string msg)
    {
        if (DeskTop != null)
            MsgBox.MessageBox(DeskTop, msg, MsgBox.mfInformation | MsgBox.mfOKButton);
    }

    // ------------------------------------------------------------------
    // Options / UI Colors — TColorDialog backed by the live TProgram palette
    // ------------------------------------------------------------------

    private void OpenUiColors()
    {
        if (DeskTop == null) return;

        // Clone the live TProgram palette so TColorDialog edits a copy.
        // TColorItem indices are 1-based positions in TProgram.cpColor:
        //   1           → TBackground (desktop fill)
        //   2, 4        → TMenuView normal / selected item
        //   8, 9        → TWindow (blue) frame / title
        //   32, 34      → TDialog frame / title
        //   41, 45      → TButton normal / default
        var pal = GetPalette().Clone();

        var groups =
            new TColorGroup("Desktop",
                new TColorItem("Background", 1)) +
            new TColorGroup("Menu",
                new TColorItem("Normal",    2) +
                new TColorItem("Selected",  4)) +
            new TColorGroup("Window",
                new TColorItem("Frame",  8) +
                new TColorItem("Title",  9)) +
            new TColorGroup("Dialog",
                new TColorItem("Frame", 32) +
                new TColorItem("Title", 34)) +
            new TColorGroup("Button",
                new TColorItem("Normal",  41) +
                new TColorItem("Default", 45));

        var dlg = new TColorDialog(pal, groups);
        if (ValidView(dlg) == null) return;

        if (DeskTop.ExecView(dlg) == Views.cmOK)
        {
            var live = GetPalette();
            TPalette? editedPalette = dlg.Pal;
            if (editedPalette == null) return;
            System.Array.Copy(editedPalette.Data, live.Data,
                System.Math.Min(editedPalette.Data.Length, live.Data.Length));
            DrawView();
        }
    }

    private string DefaultShell()
    {
        if (!string.IsNullOrWhiteSpace(_config.DefaultShell)) return _config.DefaultShell;
        return System.OperatingSystem.IsWindows()
            ? "cmd.exe"
            : (System.Environment.GetEnvironmentVariable("SHELL") ?? "/bin/sh");
    }

    // ------------------------------------------------------------------
    // Built-in demo command loop for InMemory terminals
    // ------------------------------------------------------------------

    private static void WireDemoCommandLoop(TTerminalWindow win)
    {
        var term = win.Terminal;
        term.CommandSubmitted += (_, e) =>
        {
            string cmd = e.Command.Trim();
            if (cmd.Length == 0) return;
            if (cmd.Equals("help", System.StringComparison.OrdinalIgnoreCase))
            {
                term.WriteLine("Built-in commands:");
                term.WriteLine("  help              show this help");
                term.WriteLine("  echo <text>       write text to the terminal");
                term.WriteLine("  clear | cls       clear the terminal");
                term.WriteLine("  size              show terminal size");
                term.WriteLine("Use the menu (F10) for Session/Tools/Options.");
            }
            else if (cmd.Equals("clear", System.StringComparison.OrdinalIgnoreCase) ||
                     cmd.Equals("cls",   System.StringComparison.OrdinalIgnoreCase))
            {
                term.Clear();
            }
            else if (cmd.Equals("size", System.StringComparison.OrdinalIgnoreCase))
            {
                var ts = term.TerminalSize;
                term.WriteLine($"Terminal size: {ts.Columns} x {ts.Rows}");
            }
            else if (cmd.StartsWith("echo ", System.StringComparison.OrdinalIgnoreCase))
            {
                term.WriteLine(cmd.Substring(5));
            }
            else
            {
                term.WriteLine($"Unknown command: {cmd}");
            }
        };
    }
}
