// <auto-generated> — produced by svhc.
// SharpVision Help Compiler symbol output.

namespace SharpVision;

public static class HelpCtx
{
    public const ushort hcNocontext = 0;
    public const ushort hcIndex = 1;
    public const ushort hcMainMenu = 2;
    public const ushort hcWelcomeWindow = 3;
    public const ushort hcFileMenu = 4;
    public const ushort hcWindowManagement = 5;
    public const ushort hcControlsShowcase = 6;
    public const ushort hcColorDialog = 7;
    public const ushort hcResourceDialog = 8;
    public const ushort hcResourceFiles = 9;
    public const ushort hcHelpSystem = 10;
    public const ushort hcAbout = 11;
    public const ushort hcEditorPlaceholder = 12;
}
